// app/layout.tsx
"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";
import {
  ClerkProvider,
  ClerkLoading,
  ClerkLoaded,
} from '@clerk/nextjs'
// import { ModeToggle } from "@/components/ui/ModeToggle";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isHomepage = pathname === "/";

  return (
    <ClerkProvider
      signInUrl="/signin"
      signUpUrl="/signup"
      afterSignInUrl="/dashboard"
      afterSignUpUrl="/dashboard"
    >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
            <ClerkLoading>
              {/* Optional: Add a loading spinner or message */}
              <div className="flex justify-center items-center h-screen">Loading authentication...</div>
            </ClerkLoading>
            <ClerkLoaded>
              {!isHomepage && <Navbar />}
              {/* <div className="absolute top-6 right-6"> ModeToggle will be moved out of here later */}
                {/* <ModeToggle /> */}
              {/* </div> */}
              {children}
            </ClerkLoaded>
          
        </body>
      </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
